version: '3.8'

services:
  customer-categorizer:
    build: .
    container_name: customer_categorizer
    ports:
      - "8501:8501"
    environment:
      - MONGO_DB_URL=${MONGO_DB_URL}
      - B2_APPLICATION_KEY_ID=${B2_APPLICATION_KEY_ID}
      - B2_APPLICATION_KEY=${B2_APPLICATION_KEY}
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./artifacts:/app/artifacts
    restart: unless-stopped
